# Section "InputClass"
#     Identifier "Touchpad principal"
#     MatchProduct "ELAN2204:00 04F3:3109 Touchpad"
#     MatchIsTouchpad "on"
#     Option "Tapping" "on"
#     Option "DisableWhileTyping" "on"
#     Option "NaturalScrolling" "on"
#     Option "ScrollingPixelDistance" "30"
# EndSection


# ELAN touchpad configuration
Section "InputClass"
    Identifier "ELAN Touchpad"
    MatchDriver "libinput"
    MatchProduct "ELAN2204"
    MatchIsTouchpad "on"

# Basic options
    Option "Tapping" "on"
    Option "TappingDrag" "on"
    Option "DisableWhileTyping" "on"
    Option "NaturalScrolling" "on"

# Sensitivity and scrolling
    Option "ScrollingPixelDistance" "30"

EndSection
