mode = "local"
project = ""
shell = ""

[dirs]
project = []
python = "isolated"
# data  = "..."   # to fill in. Commented out, so hatch uses its default (~/.local/share/hatch)
# cache = "..."   # to fill in. Commented out, so hatch uses its default (~/.cache/hatch)

[dirs.env]

[projects]

[publish.index]
repo = "main"

[template]
name = ""            # to fill in
email = ""           # to fill in

[template.licenses]
headers = true
default = [
    "MIT",
]

[template.plugins.default]
tests = true
ci = false
src-layout = true

[terminal.styles]
info = "bold"
success = "bold cyan"
error = "bold red"
warning = "bold yellow"
waiting = "bold magenta"
debug = "bold"
spinner = "simpleDotsScrolling"
