# Section "InputClass"
#     Identifier "Touchpad principal"
#     MatchProduct "ELAN2204:00 04F3:3109 Touchpad"
#     MatchIsTouchpad "on"
#     Option "Tapping" "on"
#     Option "DisableWhileTyping" "on"
#     Option "NaturalScrolling" "on"
#     Option "ScrollingPixelDistance" "30"
# EndSection


# Configuration touchpad ELAN
Section "InputClass"
    Identifier "ELAN Touchpad"
    MatchDriver "libinput"
    MatchProduct "ELAN2204"
    MatchIsTouchpad "on"

# Options de base
    Option "Tapping" "on"
    Option "TappingDrag" "on"
    Option "DisableWhileTyping" "on"
    Option "NaturalScrolling" "on"

# Sensibilité et scrolling
    Option "ScrollingPixelDistance" "30"

EndSection
