# ── Fenêtre ───────────────────────────────
window_padding_width 0
# background_opacity 0.98
# hide_window_decorations yes

# ── Couleurs ──────────────────────────────
background #080808
# background #0A0A0A
# background #000000

# ── Police ────────────────────────────────
font_family      Roboto Mono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

# FiraCode Nerd Font
# font_family JetBrainsMono Nerd Font

font_size 12.5

# ── Scrolling ─────────────────────────────
wheel_scroll_multiplier 3.0

map shift+up   scroll_page_up
map shift+down scroll_page_down
map page_up    scroll_page_up
map page_down  scroll_page_down

scrollbar never
text_composition_strategy legacy
cursor_shape block
shell_integration no-cursor
enable_audio_bell no
cursor_blink_interval 0
cursor none

input_delay 0
repaint_delay 3
sync_to_monitor no
