font_family              FiraCode Nerd Font
bold_font                FiraCode Nerd Font
italic_font              FiraCode Nerd Font
bold_italic_font         FiraCode Nerd Font

force_ltr                yes
